# docker-compose.yml
services:
  db:
    image: mysql:8.0
    container_name: malvader_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aluc4rd3       # Senha para o usuário root
      MYSQL_DATABASE: banco_malvader
      MYSQL_USER: malvader_user          # <-- NOVO USUÁRIO
      MYSQL_PASSWORD: malvader_password  # <-- NOVA SENHA para o novo usuário
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: {}